#!/usr/bin/env python3
"""Spike: can we see Codex thread UUIDs on the remote app-server wire?

Conclusion (see VERDICT at bottom of --help): YES we can peek them, NO that does
not give Claude-style per-thread sandbox routing without a full RPC demuxer.

What Desktop actually does for an SSH host (from app.asar AppServerTransportSshWebsocket):

  1. ssh …  → probe `command -v codex`
  2. ssh …  → `nohup codex … app-server --listen unix://…desktop-ssh-websocket-v0.sock &`
  3. ssh -T … `codex app-server proxy`   # stdio after a random sync marker
       └─ WebSocket client over that SSH duplex → ONE remote app-server
  4. All threads multiplex as JSON-RPC on that single websocket

So the peek point is wrapping step 3 (`codex app-server proxy`), not SSH ForceCommand.

Usage (on a machine/sandbox where Desktop will call `codex app-server proxy`):

  # Install as a shim in front of real codex, then reconnect Codex Desktop SSH:
  CODEX_REAL=/usr/local/bin/codex.real ./peek-app-server-ws.py install-shim ~/.local/bin/codex
  # Logs JSON-RPC methods + threadIds to ~/.codex-cloud-spike/ws-peek.jsonl

  # Or parse a captured cleartext JSON-RPC dump:
  ./peek-app-server-ws.py parse-jsonl dump.jsonl
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Iterator

UUID_RE = re.compile(
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I
)

VERDICT = """
VERDICT
=======
Peeking: cheap. Desktop's remote path is `codex app-server proxy` over SSH stdio
as a websocket. threadId shows up on thread/resume, turn/start, turn/steer, and
~80 protocol types. thread/start does NOT send a client id; the server mints it
in the response.

Routing: expensive. One app-server process owns every thread on that host.
Host-scoped methods (fs/*, command/exec, gitDiffToRemote) have no threadId, so
even a perfect RPC demux cannot isolate the file pane / shell without inventing
affinity. Tool execution also runs inside that one process — seeing a UUID does
not move the cwd or filesystem.

Claude comparison: Claude puts the UUID in SSH_ORIGINAL_COMMAND (and ccd-cli
stdin). Codex puts it only inside a multiplexed app-server websocket. A Claude-
style ForceCommand router will never see it.

Practical path for crafting-codex: Cursor-style binder (concrete alias → sandbox),
not a per-thread router.
"""


def extract_thread_ids(obj: Any) -> list[str]:
    found: list[str] = []

    def walk(o: Any) -> None:
        if isinstance(o, dict):
            for k, v in o.items():
                if k in ("threadId", "thread_id", "id", "sessionId") and isinstance(v, str):
                    if UUID_RE.fullmatch(v):
                        found.append(f"{k}={v}")
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)
        elif isinstance(o, str):
            # ignore free-text; too noisy
            pass

    walk(obj)
    return found


def summarize_rpc(obj: dict[str, Any]) -> str:
    method = obj.get("method")
    if method:
        ids = extract_thread_ids(obj.get("params"))
        return f"→ {method} {' '.join(ids)}"
    if "result" in obj:
        ids = extract_thread_ids(obj.get("result"))
        return f"← result id={obj.get('id')!r} {' '.join(ids)}"
    if "error" in obj:
        return f"← error id={obj.get('id')!r} {obj.get('error')}"
    return f"? keys={sorted(obj.keys())}"


def iter_json_objects(text: str) -> Iterator[dict[str, Any]]:
    # NDJSON or concatenated objects
    for line in text.splitlines():
        line = line.strip()
        if not line or not line.startswith("{"):
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict):
            yield obj


def cmd_parse_jsonl(path: Path) -> int:
    text = path.read_text(errors="replace")
    n = 0
    for obj in iter_json_objects(text):
        print(summarize_rpc(obj))
        n += 1
    print(f"# parsed {n} objects from {path}", file=sys.stderr)
    return 0


def cmd_scan_text(path: Path) -> int:
    """Brute scan: print lines/methods that mention thread RPCs or UUIDs near them."""
    text = path.read_text(errors="replace")
    interesting = ("thread/start", "thread/resume", "turn/start", "threadId", "sessionId")
    for i, line in enumerate(text.splitlines(), 1):
        if any(x in line for x in interesting) or (
            "thread/" in line and UUID_RE.search(line)
        ):
            print(f"{i}: {line[:300]}")
    return 0


SHIM = r'''#!/usr/bin/env bash
# Generated by peek-app-server-ws.py — logs app-server proxy JSON-RPC if possible.
set -euo pipefail
REAL="${CODEX_REAL:-__REAL__}"
LOG_DIR="${CODEX_SPIKE_LOG_DIR:-$HOME/.codex-cloud-spike}"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/proxy-$(date -u +%Y%m%dT%H%M%SZ)-$$.log"

# Only intercept the proxy path Desktop uses for SSH websocket.
if [[ "${1:-}" == "app-server" && "${2:-}" == "proxy" ]]; then
  # Tee raw stdio. Websocket frames will be binary-ish; still enough to rg for
  # "thread/start", "threadId", etc. after a session.
  exec > >(tee -a "$LOG" >/dev/null) 2> >(tee -a "$LOG.err" >&2)
  printf 'PEEK start %s args=%q ' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >>"$LOG.meta"
  printf ' cwd=%q\n' "$(pwd)" >>"$LOG.meta"
  # Prefer a python tee that preserves bytes both ways if available.
  if command -v python3 >/dev/null 2>&1; then
    exec python3 - "$REAL" "$@" <<'PY'
import os, sys, subprocess, threading
real, args = sys.argv[1], sys.argv[2:]
log = os.environ.get("CODEX_SPIKE_RAW", "")
# Parent exported LOG via env? fall back
log = os.environ.get("CODEX_SPIKE_RAW_LOG") or (os.path.expanduser("~/.codex-cloud-spike/proxy-raw-$$.bin"))
# Actually get path from fd? Use env set below.
log = os.environ["CODEX_SPIKE_RAW_LOG"]
proc = subprocess.Popen([real, *args], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def pump(src, dst, mirror):
    while True:
        chunk = src.read(8192)
        if not chunk:
            break
        mirror.write(chunk); mirror.flush()
        dst.write(chunk); dst.flush()

with open(log, "ab") as mirror:
    t1 = threading.Thread(target=pump, args=(sys.stdin.buffer, proc.stdin, mirror), daemon=True)
    t2 = threading.Thread(target=pump, args=(proc.stdout, sys.stdout.buffer, mirror), daemon=True)
    t3 = threading.Thread(target=pump, args=(proc.stderr, sys.stderr.buffer, mirror), daemon=True)
    t1.start(); t2.start(); t3.start()
    sys.exit(proc.wait())
PY
  fi
fi
exec "$REAL" "$@"
'''


def cmd_install_shim(dest: Path) -> int:
    real = os.environ.get("CODEX_REAL")
    if not real:
        which = shutil.which("codex")
        print("Set CODEX_REAL to the real codex binary path first.", file=sys.stderr)
        print(f"hint: currently `codex` => {which}", file=sys.stderr)
        return 2
    real_path = Path(real).resolve()
    dest = dest.expanduser()
    dest.parent.mkdir(parents=True, exist_ok=True)
    body = SHIM.replace("__REAL__", str(real_path))
    # Fix the python tee env: inject RAW log path setup before exec python
    body = body.replace(
        'if command -v python3 >/dev/null 2>&1; then\n    exec python3',
        'if command -v python3 >/dev/null 2>&1; then\n'
        '  export CODEX_SPIKE_RAW_LOG="$LOG.raw"\n'
        '  exec python3',
    )
    dest.write_text(body)
    dest.chmod(0o755)
    print(f"wrote shim {dest}")
    print(f"real binary {real_path}")
    print("Put the shim earlier on PATH than the real codex, reconnect SSH in Codex Desktop,")
    print("then inspect ~/.codex-cloud-spike/*.raw with: this-script scan-text FILE")
    return 0


def cmd_verdict() -> int:
    print(VERDICT)
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("verdict", help="print the spike conclusion")
    s = sub.add_parser("parse-jsonl", help="summarize NDJSON RPC objects")
    s.add_argument("path", type=Path)
    s = sub.add_parser("scan-text", help="grep-like scan of a raw proxy capture")
    s.add_argument("path", type=Path)
    s = sub.add_parser("install-shim", help="write a PATH shim that tees app-server proxy")
    s.add_argument("dest", type=Path, help="e.g. ~/.local/bin/codex")
    args = p.parse_args()
    if args.cmd == "verdict":
        return cmd_verdict()
    if args.cmd == "parse-jsonl":
        return cmd_parse_jsonl(args.path)
    if args.cmd == "scan-text":
        return cmd_scan_text(args.path)
    if args.cmd == "install-shim":
        return cmd_install_shim(args.dest)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
