#!/usr/bin/env python3
"""Generate the Crafting templates for the router and its workers.

The sandboxes run this repo from a checkout, so the templates stay small: a
checkout, the `{{secret ...}}` renders (which only resolve template-side), the
org-specific config block, and one on_create line that runs sandbox-setup.sh
from the checkout. Everything org- or site-specific is read from
codex-cloud.conf, which bootstrap.sh writes, so the generated templates carry
no defaults of ours.
"""

import os
import pathlib
import shlex
import sys

ROOT = pathlib.Path(__file__).resolve().parent
OUT_DIR = ROOT / "templates"
CONF = pathlib.Path(os.environ.get("CODEX_CLOUD_CONF", ROOT / "codex-cloud.conf"))

BASE_SNAPSHOT = os.environ.get(
    "CODEX_BASE_SNAPSHOT",
    "oci://us-docker.pkg.dev/crafting-eng/pub/sandbox/workspace/default:latest",
)
ROUTER_HOME = "/home/owner/.codex-router"

# Where the checkout of this repo lands in every sandbox. sandbox-setup.sh
# works from wherever it is, but the daemon entry below needs a literal path.
SRC = "/home/owner/crafting-codex"

DEFAULTS = {
    "CODEX_ROUTER_ORG": "",
    "CODEX_ROUTER_REPO": "https://github.com/crafting-demo/crafting-codex",
    "CODEX_ROUTER_SERVER_URL": "",
    "CODEX_ROUTER_DNS_SUFFIX": "",
    "CODEX_ROUTER_WORKSPACE": "router",
    "CODEX_ROUTER_TEMPLATE": "codex-worker",
    "CODEX_ROUTER_WORKER_WORKSPACE": "dev",
    "CODEX_ROUTER_PREFIX": "cx",
    "CODEX_ROUTER_TOKEN_SECRET": "codex-router-token",
    "CODEX_ROUTER_WORKER_PORT": "8383",
    "CODEX_OPENAI_SECRET": "",
    "CODEX_WORKER_REPO": "",
    "CODEX_WORKER_CHECKOUT": "",
    "CODEX_START_DIR": "/home/owner",
}


def conf() -> dict:
    """Read codex-cloud.conf, letting the environment override it."""
    values = dict(DEFAULTS)
    if CONF.exists():
        for line in CONF.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, raw = line.split("=", 1)
            if key in values:
                values[key] = shlex.split(raw)[0] if raw else ""
    for key in values:
        if os.environ.get(key):
            values[key] = os.environ[key]
    missing = [k for k in ("CODEX_ROUTER_ORG", "CODEX_ROUTER_SERVER_URL") if not values[k]]
    if missing:
        sys.exit(f"{', '.join(missing)} not set -- run ./bootstrap.sh first")
    return values


def block(text: str, indent: int) -> str:
    """Render text as a YAML literal block scalar body at the given indent."""
    pad = " " * indent
    lines = text.split("\n")
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(pad + line if line else "" for line in lines)


def setup_file(path, mode, content=None, template=None, overwrite=True):
    key = "content" if content is not None else "template"
    body = content if content is not None else template
    return (
        f"        - path: {path}\n"
        f"          owner: '1000:1000'\n"
        f"          mode: '{mode}'\n"
        f"          overwrite: {'true' if overwrite else 'false'}\n"
        f"          {key}: |\n"
        f"{block(body, 12)}\n"
    )


def router_template(cfg: dict) -> str:
    router_config = "\n".join(
        [
            "# Sourced by lib/worker.sh and everything under bin/.",
            f"CODEX_ROUTER_ORG={cfg['CODEX_ROUTER_ORG']}",
            f"CODEX_ROUTER_TEMPLATE={cfg['CODEX_ROUTER_TEMPLATE']}",
            f"CODEX_ROUTER_WORKER_WORKSPACE={cfg['CODEX_ROUTER_WORKER_WORKSPACE']}",
            f"CODEX_ROUTER_PREFIX={cfg['CODEX_ROUTER_PREFIX']}",
            f"CODEX_ROUTER_SERVER_URL={cfg['CODEX_ROUTER_SERVER_URL']}",
            f"CODEX_ROUTER_DNS_SUFFIX={cfg['CODEX_ROUTER_DNS_SUFFIX']}",
            f"CODEX_ROUTER_WORKER_PORT={cfg['CODEX_ROUTER_WORKER_PORT']}",
            f"CODEX_START_DIR={cfg['CODEX_START_DIR']}",
            "",
        ]
    )

    files = [
        setup_file(f"{ROUTER_HOME}/config", "0644", content=router_config),
        # Rendered from org secrets so no credential lives in the template.
        setup_file(
            f"{ROUTER_HOME}/etc/cs-login-token",
            "0600",
            template='{{secret "%s"}}' % cfg["CODEX_ROUTER_TOKEN_SECRET"],
        ),
    ]
    if cfg["CODEX_OPENAI_SECRET"]:
        files.append(
            setup_file(
                f"{ROUTER_HOME}/etc/openai-key",
                "0600",
                template='{{secret "%s"}}' % cfg["CODEX_OPENAI_SECRET"],
            )
        )

    return f"""\
# Generated by build-template.py -- the scripts live in the repo, not here.
#
# The router sandbox is the concrete SSH host Codex App connects to. It runs no
# threads of its own: the shim takes over the app-server that Codex Desktop
# starts here, and the demux behind it gives every thread its own worker
# sandbox. All of that code comes from the checkout below; updating a running
# router is `git pull` there, not a template change.
workspaces:
  - name: {cfg['CODEX_ROUTER_WORKSPACE']}
    description: Codex app-server router (per-thread sandbox dispatcher).
    base_snapshot: {BASE_SNAPSHOT}
    checkouts:
      - path: crafting-codex
        repo:
          git: {cfg['CODEX_ROUTER_REPO']}
    env:
      - SHELL=/bin/bash
      - PATH=/usr/local/go/bin:/usr/local/node/bin:$HOME/.local/bin:$PATH
    system:
      files:
{"".join(files)}      daemons:
        - name: codex-router-init
          run:
            cmd: {SRC}/router/bin/codex-router-init
    lifecycle:
      on_create:
        run:
          cmd: {SRC}/sandbox-setup.sh router
        max_retries: 2
        timeout: 10m0s
"""


def worker_template(cfg: dict) -> str:
    """The sandbox a thread actually runs in.

    Plain by design: whatever you would want in a dev sandbox belongs here. The
    only thing the router requires of it is a `codex` on PATH that is already
    signed in, which sandbox-setup.sh takes care of from the checkout.
    """
    checkouts = ""
    if cfg["CODEX_WORKER_REPO"]:
        checkouts = f"""\
      - path: {cfg['CODEX_WORKER_CHECKOUT']}
        repo:
          git: {cfg['CODEX_WORKER_REPO']}
"""

    files = ""
    if cfg["CODEX_OPENAI_SECRET"]:
        files = f"""\
    system:
      files:
{setup_file("/home/owner/.codex-worker/openai-key", "0600",
            template='{{secret "%s"}}' % cfg["CODEX_OPENAI_SECRET"])}\
"""

    return f"""\
# Generated by build-template.py -- run ./bootstrap.sh to change the checkout.
#
# This template is yours to change: add services, containers, or dependencies
# the way you would to any Crafting template, and every Codex thread gets them.
# Once you edit it, bootstrap notices and stops regenerating it over your
# changes.
#
# Workers are claimed from a pool so a new thread gets a sandbox in about a
# second rather than a full build.
workspaces:
  - name: {cfg['CODEX_ROUTER_WORKER_WORKSPACE']}
    description: Codex worker workspace.
    checkouts:
{checkouts}\
      - path: crafting-codex
        repo:
          git: {cfg['CODEX_ROUTER_REPO']}
    base_snapshot: {BASE_SNAPSHOT}
    env:
      - SHELL=/bin/bash
      - PATH=/usr/local/go/bin:/usr/local/node/bin:$HOME/.local/bin:$PATH
{files}\
    lifecycle:
      on_create:
        run:
          cmd: {SRC}/sandbox-setup.sh worker
        max_retries: 2
        timeout: 10m0s
customizations:
  - detach_env:
      enabled: true
"""


def main() -> int:
    cfg = conf()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in (
        ("codex-router.yaml", router_template(cfg)),
        ("codex-worker.yaml", worker_template(cfg)),
    ):
        out = OUT_DIR / name
        out.write_text(text)
        print(f"wrote {out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
